### PR TITLE
remove sorted ligrec plot

### PR DESCRIPTION
**Pull request by wangjiawen2013**
Don't sorted label_rankge keys according to issues https://github.com/scverse/squidpy/issues/560#issuecomment-1152842944

### CODE REVIEW

**Comment by giovp** [comment]
hi @wangjiawen2013 , can you give me write access to your fork? I found the right line to fix it, you need to remove `sorted` from here:
https://github.com/scverse/squidpy/blob/81b307d6e0696870125b1ccfc3a2fcff51b09b11/squidpy/gr/_ligrec.py#L388-L393

and not from the plotting. I could quickly wrap up the PR but I need you to grant me write access to your fork, otherwise I cannot push on this PR.

@michalk8 if you could quickly double check that removing `sorted` in that line doesn't mess up with rest of function downstream would be appreciated (although it shouldnt'). Thank you!

**Comment by wangjiawen2013** [comment]
> hi @wangjiawen2013 , can you give me write access to your fork? I found the right line to fix it, you need to remove `sorted` from here: https://github.com/scverse/squidpy/blob/81b307d6e0696870125b1ccfc3a2fcff51b09b11/squidpy/gr/_ligrec.py#L388-L393
> 
> and not from the plotting. I could quickly wrap up the PR but I need you to grant me write access to your fork, otherwise I cannot push on this PR.
> 
> @michalk8 if you could quickly double check that removing `sorted` in that line doesn't mess up with rest of function downstream would be appreciated (although it shouldnt'). Thank you!

I have

**Comment by wangjiawen2013** [comment]
> hi @wangjiawen2013 , can you give me write access to your fork? I found the right line to fix it, you need to remove `sorted` from here: https://github.com/scverse/squidpy/blob/81b307d6e0696870125b1ccfc3a2fcff51b09b11/squidpy/gr/_ligrec.py#L388-L393
> 
> and not from the plotting. I could quickly wrap up the PR but I need you to grant me write access to your fork, otherwise I cannot push on this PR.
> 
> @michalk8 if you could quickly double check that removing `sorted` in that line doesn't mess up with rest of function downstream would be appreciated (although it shouldnt'). Thank you!

I don't know how to give you access right, but I have added you to my fork: https://github.com/wangjiawen2013/squidpy
hope it will help !

**Comment by giovp** [comment]
@wangjiawen2013 can you re-opne this PR?

**Comment by giovp** [comment]
actually no problem, opened a new one!

**Pull request closed without merging**
